"""Generate the single importable blueprint from the standalone script."""

from pathlib import Path
import argparse
from copy import deepcopy
import yaml

ROOT = Path(__file__).resolve().parents[1]


class ScriptDumper(yaml.SafeDumper):
    """Keep multiline Jinja readable."""


class Input(str):
    """Blueprint input placeholder."""


ScriptDumper.add_representer(str, lambda dumper, value: dumper.represent_scalar(
    "tag:yaml.org,2002:str", value, style="|" if "\n" in value else None
))
ScriptDumper.add_representer(Input, lambda dumper, value: dumper.represent_scalar("!input", str(value)))


def build():
    script = yaml.safe_load((ROOT / "holiday-atmosphere.yaml").read_text())
    inputs = {
        "default_lights": {
            "name": "Lights",
            "description": "Choose your usual lights once. You can override them when running the script.",
            "default": [],
            "selector": deepcopy(script["fields"]["lights"]["selector"]),
        },
        "default_effect": {
            "name": "Default effect",
            "description": "You can choose another effect each time you run the script.",
            "default": "xmas_fireplace",
            "selector": deepcopy(script["fields"]["effect"]["selector"]),
        },
    }
    script["variables"] = {name: Input(name) for name in inputs}
    blueprint = {
        "blueprint": {
            "name": "Holiday Atmosphere v2.1 — All Holidays",
            "description": "Install this one script for all 16 holiday effects. No helpers, companion scripts, packages, or configuration edits. Choose your lights and default effect, save, and run. Calling it again switches effects; choose stop to restore the original lighting.",
            "domain": "script",
            "source_url": "https://github.com/ste-ta/holiday-atmosphere-scripts-for-home-assistant/blob/main/blueprints/script/holiday_atmosphere.yaml",
            "homeassistant": {"min_version": "2025.1.4"},
            "input": inputs,
        },
        **script,
    }
    return "# Generated by tools/build_blueprint.py; edit holiday-atmosphere.yaml.\n" + yaml.dump(
        blueprint, Dumper=ScriptDumper, sort_keys=False, allow_unicode=True, width=100
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    destination = ROOT / "blueprints/script/holiday_atmosphere.yaml"
    content = build()
    if args.check:
        if not destination.exists() or destination.read_text() != content:
            raise SystemExit("Blueprint is stale; run python tools/build_blueprint.py")
    else:
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content)
