"""Build the installable Home Assistant package from the editable script files."""

from pathlib import Path
import argparse
import yaml

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = {
    "holiday_atmosphere_controller": "holiday-atmosphere-controller.yaml",
    "holiday_atmosphere_runner": "holiday-atmosphere-runner.yaml",
    "holiday_atmosphere_light_step": "holiday-atmosphere-light-step.yaml",
    "halloween_atmosphere": "halloween-athmosphere.yaml",
    "christmas_atmosphere": "christmas-athmosphere-script.yaml",
    "newyear_atmosphere": "newyear-athmosphere-script.yaml",
}


class ScriptDumper(yaml.SafeDumper):
    """Keep multiline Jinja readable in the distributable package."""


def represent_string(dumper, value):
    return dumper.represent_scalar("tag:yaml.org,2002:str", value, style="|" if "\n" in value else None)


ScriptDumper.add_representer(str, represent_string)


def build():
    package = {
        "input_text": {
            "holiday_atmosphere_session": {
                "name": "Holiday Atmosphere Session",
                "max": 255,
                "initial": "{}",
            }
        },
        "script": {name: yaml.safe_load((ROOT / file).read_text()) for name, file in SCRIPTS.items()},
    }
    return "# Generated by tools/build_package.py; edit the source scripts.\n" + yaml.dump(
        package, Dumper=ScriptDumper, sort_keys=False, allow_unicode=True, width=100
    )


def build_core_blueprints():
    """Native import cannot provision multiple entities; offer one link per core script."""
    result = {}
    for name, filename in list(SCRIPTS.items())[:3]:
        script = yaml.safe_load((ROOT / filename).read_text())
        blueprint = {
            "blueprint": {
                "name": f"{script['alias']} — Core v2.1",
                "description": (
                    f"Shared Holiday Atmosphere v2.1 core script. Create exactly one script with entity ID "
                    f"script.{name}. Install the other two core scripts and "
                    "input_text.holiday_atmosphere_session before creating room presets. "
                    "Do not run this internal script directly."
                ),
                "domain": "script",
                "source_url": (
                    "https://github.com/ste-ta/holiday-atmosphere-scripts-for-home-assistant/"
                    f"blob/main/blueprints/script/{name}.yaml"
                ),
                "homeassistant": {"min_version": "2025.1.4"},
            },
            **script,
        }
        result[ROOT / f"blueprints/script/{name}.yaml"] = (
            "# Generated by tools/build_package.py; edit the source script.\n"
            + yaml.dump(blueprint, Dumper=ScriptDumper, sort_keys=False, allow_unicode=True, width=100)
        )
    return result


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = {ROOT / "packages/holiday_atmosphere.yaml": build(), **build_core_blueprints()}
    for destination, content in outputs.items():
        if args.check:
            if not destination.exists() or destination.read_text() != content:
                raise SystemExit(f"{destination.name} is stale; run python tools/build_package.py")
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(content)
